version: '3.1'

services:
  app:
    image: 'pichincha/backend'
    build: backend/
    ports:
      - 8080:8080
  web:
    image: 'pichincha/frontend'
    build: frontend/
    ports:
      - 3000:80
